/** Generated by `pnpm setup`; do not select a preset at runtime. */
export const ACTIVE_CAPABILITY_PRESET = 'demo' as const;

export const ENABLED_CAPABILITY_IDS = [
  'audit',
  'email',
  'auth',
  'profile',
  'user',
  'genre',
  'book',
] as const;

const enabledCapabilities = new Set<string>(ENABLED_CAPABILITY_IDS);

export const isCapabilityEnabled = (capabilityId: string) =>
  enabledCapabilities.has(capabilityId);
