/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTelemetrySentryTunnelRouteImport } from './routes/api/telemetry.sentry-tunnel'
import { Route as ApiTelemetryLogsRouteImport } from './routes/api/telemetry.logs'
import { Route as ApiTelemetryOtelV1TracesRouteImport } from './routes/api/telemetry.otel.v1.traces'
import { Route as ApiTelemetryOtelV1MetricsRouteImport } from './routes/api/telemetry.otel.v1.metrics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetrySentryTunnelRoute =
  ApiTelemetrySentryTunnelRouteImport.update({
    id: '/api/telemetry/sentry-tunnel',
    path: '/api/telemetry/sentry-tunnel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTelemetryLogsRoute = ApiTelemetryLogsRouteImport.update({
  id: '/api/telemetry/logs',
  path: '/api/telemetry/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetryOtelV1TracesRoute =
  ApiTelemetryOtelV1TracesRouteImport.update({
    id: '/api/telemetry/otel/v1/traces',
    path: '/api/telemetry/otel/v1/traces',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTelemetryOtelV1MetricsRoute =
  ApiTelemetryOtelV1MetricsRouteImport.update({
    id: '/api/telemetry/otel/v1/metrics',
    path: '/api/telemetry/otel/v1/metrics',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/telemetry/logs': typeof ApiTelemetryLogsRoute
  '/api/telemetry/sentry-tunnel': typeof ApiTelemetrySentryTunnelRoute
  '/api/telemetry/otel/v1/metrics': typeof ApiTelemetryOtelV1MetricsRoute
  '/api/telemetry/otel/v1/traces': typeof ApiTelemetryOtelV1TracesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/telemetry/logs': typeof ApiTelemetryLogsRoute
  '/api/telemetry/sentry-tunnel': typeof ApiTelemetrySentryTunnelRoute
  '/api/telemetry/otel/v1/metrics': typeof ApiTelemetryOtelV1MetricsRoute
  '/api/telemetry/otel/v1/traces': typeof ApiTelemetryOtelV1TracesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/telemetry/logs': typeof ApiTelemetryLogsRoute
  '/api/telemetry/sentry-tunnel': typeof ApiTelemetrySentryTunnelRoute
  '/api/telemetry/otel/v1/metrics': typeof ApiTelemetryOtelV1MetricsRoute
  '/api/telemetry/otel/v1/traces': typeof ApiTelemetryOtelV1TracesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/telemetry/logs'
    | '/api/telemetry/sentry-tunnel'
    | '/api/telemetry/otel/v1/metrics'
    | '/api/telemetry/otel/v1/traces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/telemetry/logs'
    | '/api/telemetry/sentry-tunnel'
    | '/api/telemetry/otel/v1/metrics'
    | '/api/telemetry/otel/v1/traces'
  id:
    | '__root__'
    | '/'
    | '/api/telemetry/logs'
    | '/api/telemetry/sentry-tunnel'
    | '/api/telemetry/otel/v1/metrics'
    | '/api/telemetry/otel/v1/traces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTelemetryLogsRoute: typeof ApiTelemetryLogsRoute
  ApiTelemetrySentryTunnelRoute: typeof ApiTelemetrySentryTunnelRoute
  ApiTelemetryOtelV1MetricsRoute: typeof ApiTelemetryOtelV1MetricsRoute
  ApiTelemetryOtelV1TracesRoute: typeof ApiTelemetryOtelV1TracesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry/sentry-tunnel': {
      id: '/api/telemetry/sentry-tunnel'
      path: '/api/telemetry/sentry-tunnel'
      fullPath: '/api/telemetry/sentry-tunnel'
      preLoaderRoute: typeof ApiTelemetrySentryTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry/logs': {
      id: '/api/telemetry/logs'
      path: '/api/telemetry/logs'
      fullPath: '/api/telemetry/logs'
      preLoaderRoute: typeof ApiTelemetryLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry/otel/v1/traces': {
      id: '/api/telemetry/otel/v1/traces'
      path: '/api/telemetry/otel/v1/traces'
      fullPath: '/api/telemetry/otel/v1/traces'
      preLoaderRoute: typeof ApiTelemetryOtelV1TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry/otel/v1/metrics': {
      id: '/api/telemetry/otel/v1/metrics'
      path: '/api/telemetry/otel/v1/metrics'
      fullPath: '/api/telemetry/otel/v1/metrics'
      preLoaderRoute: typeof ApiTelemetryOtelV1MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTelemetryLogsRoute: ApiTelemetryLogsRoute,
  ApiTelemetrySentryTunnelRoute: ApiTelemetrySentryTunnelRoute,
  ApiTelemetryOtelV1MetricsRoute: ApiTelemetryOtelV1MetricsRoute,
  ApiTelemetryOtelV1TracesRoute: ApiTelemetryOtelV1TracesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
