import { z } from 'zod';

import {
  applicationIdentitySchema,
  parseApplicationIdentity,
} from '@/platform/env/application-identity';
import type { RuntimeEnv } from '@/platform/env/runtime';

import { ACTIVE_CAPABILITY_PRESET } from '../../domain/capability-selection.generated';

import { parseEnv } from './env-schema';

const capabilityPresetSchema = z.enum(['core', 'demo']);
const applicationConfigEnvSchema = applicationIdentitySchema
  .extend({
    CAPABILITY_PRESET: capabilityPresetSchema,
  })
  .passthrough()
  .refine(
    ({ CAPABILITY_PRESET }) => CAPABILITY_PRESET === ACTIVE_CAPABILITY_PRESET,
    {
      path: ['CAPABILITY_PRESET'],
      message:
        'CAPABILITY_PRESET must match the capability selection generated by pnpm setup',
    }
  );

export type ApplicationConfig = Readonly<{
  identity: ReturnType<typeof parseApplicationIdentity>;
  preset: z.infer<typeof capabilityPresetSchema>;
}>;

export const getApplicationConfig = (
  source?: RuntimeEnv
): ApplicationConfig => {
  const env = parseEnv(applicationConfigEnvSchema, source);
  return {
    identity: parseApplicationIdentity(env),
    preset: capabilityPresetSchema.parse(env.CAPABILITY_PRESET),
  };
};

export const getApplicationIdentity = (source?: RuntimeEnv) =>
  getApplicationConfig(source).identity;

export const getCapabilityPreset = (source?: RuntimeEnv) =>
  getApplicationConfig(source).preset;
